In [27]:
import os, sys, math, random, time
from datetime import datetime
import _pickle as pickle

import numpy as np
import pandas as pd

import mxnet as mx
from mxnet import autograd, gluon, nd, gpu
from mxnet.gluon import nn

from simple_tcn_multi_channel_multi_output_correct import TCN
from trainer_small import nn_trainer

### The input dataset
ctx = mx.gpu(3)
with open('/home/chenyixiong4/TCN_traffic/data/tensor_prepare_alldata.pkl', 'rb') as f:
    [trainX_dt,train_X2_dt, trainY_dt,testX_dt, test_X2_dt,testY_dt] = pickle.load(f)

In [24]:
(test_X2_dt[0,:,-1])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,  0.,  1.,
        2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23.,  0.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.,
       17., 18., 19., 20., 21., 22., 23.,  0.,  1.,  2.,  3.,  4.,  5.,
        6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
       19., 20., 21., 22., 23.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
        8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.,
       21., 22., 23.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,
       10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
       12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,  0.,
        1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12

In [2]:
2*(1+2+4+8)*5

150

In [3]:
sub_train_X, sub_train_Y = nd.array(trainX_dt, ctx=ctx), nd.array(trainY_dt, ctx=ctx)
sub_valid_X, sub_valid_Y = nd.array(testX_dt, ctx=ctx), nd.array(testY_dt, ctx=ctx)
conv_train_X, conv_valid_X = nd.array(train_X2_dt,ctx=ctx), nd.array(test_X2_dt,ctx=ctx)

sub_train_nd = gluon.data.ArrayDataset(conv_train_X, sub_train_X, sub_train_Y)

In [17]:
conv_valid_X[7:15,:,0]


[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]]
<NDArray 8x192 @gpu(3)>

In [5]:
6741/7

963.0

In [42]:
a = [0,1]

In [45]:
np.array(range(10)).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [46]:
np.array(range(10)).reshape(5,2)[[0,2]]

array([[0, 1],
       [4, 5]])

In [4]:
len(sub_train_nd)

410238

In [5]:
"""
conv_x = conv_train_X[:128,:]
x = sub_train_X[:128,]
"""
model1 = TCN()
#choose parameters
batch_size= 128
n_epochs=500
"""
The model training
"""
### The model parameters
abs_loss = gluon.loss.L1Loss()
L2_loss = gluon.loss.L2Loss()
huber_loss = gluon.loss.HuberLoss()
initializer = mx.initializer.MSRAPrelu()
optimizer = 'adam';
optimizer_params = {'learning_rate': 0.01}

trainer_params_list = {'batch_size': batch_size,'epoch_num':n_epochs,
                'loss_func': huber_loss, 'initializer': initializer,
                'optimizer':optimizer, 'optimizer_params':optimizer_params}
train_mark='testing'
nn_trainer(train_mark, model1, sub_train_nd, conv_valid_X,sub_valid_X, sub_valid_Y, trainer_params_list=trainer_params_list, ctx=ctx)

training_data_nb: 164096
Epoch 0, valid loss: 1600.755127 valid ND: 0.218326, valid NRMSE 0.472904, valid ND new: 0.218319, valid NRMSE new 0.472894
total_time: 148.445556640625
training_data_nb: 164096
Epoch 1, valid loss: 1281.162964 valid ND: 0.182274, valid NRMSE 0.425153, valid ND new: 0.182266, valid NRMSE new 0.425139
total_time: 148.45902180671692
training_data_nb: 164096
Epoch 2, valid loss: 1598.224854 valid ND: 0.234166, valid NRMSE 0.465884, valid ND new: 0.234157, valid NRMSE new 0.465866
total_time: 148.51316022872925
training_data_nb: 164096
Epoch 3, valid loss: 1332.728638 valid ND: 0.222123, valid NRMSE 0.429566, valid ND new: 0.222114, valid NRMSE new 0.429549
total_time: 148.3949282169342
training_data_nb: 164096
Epoch 4, valid loss: 1186.377808 valid ND: 0.149560, valid NRMSE 0.411676, valid ND new: 0.149552, valid NRMSE new 0.411662
total_time: 149.78761887550354
training_data_nb: 164096
Epoch 5, valid loss: 1158.924561 valid ND: 0.156764, valid NRMSE 0.406737, val

training_data_nb: 164096
Epoch 46, valid loss: 1016.497314 valid ND: 0.144668, valid NRMSE 0.381356, valid ND new: 0.144660, valid NRMSE new 0.381339
total_time: 148.89758729934692
training_data_nb: 164096
Epoch 47, valid loss: 1035.923096 valid ND: 0.142749, valid NRMSE 0.385704, valid ND new: 0.142741, valid NRMSE new 0.385690
total_time: 148.69935083389282
training_data_nb: 164096
Epoch 48, valid loss: 1085.542480 valid ND: 0.161628, valid NRMSE 0.392026, valid ND new: 0.161619, valid NRMSE new 0.392007
total_time: 148.8580780029297
training_data_nb: 164096
Epoch 49, valid loss: 1013.580139 valid ND: 0.141170, valid NRMSE 0.380637, valid ND new: 0.141161, valid NRMSE new 0.380620
total_time: 149.5129759311676
training_data_nb: 164096
Epoch 50, valid loss: 990.601746 valid ND: 0.131724, valid NRMSE 0.377585, valid ND new: 0.131715, valid NRMSE new 0.377568
total_time: 147.74878311157227
training_data_nb: 164096
Epoch 51, valid loss: 1068.616943 valid ND: 0.161556, valid NRMSE 0.38945

KeyboardInterrupt: 

In [ ]:
Epoch 51, valid loss: 932.307922 valid ND: 0.128468, valid NRMSE 0.365086, 

In [ ]:
0.125 0.365

In [ ]:
Epoch 87, valid loss: 933.109070 valid ND: 0.130246, valid NRMSE 0.364919, 